// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtDQ4e7XVhtZGjyp4ZVUo8R8rJtlagiz4',
    appId: '1:503549612121:web:25352baa16a0336fb8e148',
    messagingSenderId: '503549612121',
    projectId: 'chat-app-a4cde',
    authDomain: 'chat-app-a4cde.firebaseapp.com',
    storageBucket: 'chat-app-a4cde.firebasestorage.app',
    measurementId: 'G-XBST3J50WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC50oa6Yef1k0vdMCczIc8DNZRBX66Je2E',
    appId: '1:503549612121:android:66bccb622fc52692b8e148',
    messagingSenderId: '503549612121',
    projectId: 'chat-app-a4cde',
    storageBucket: 'chat-app-a4cde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-rvbGgMZLIHEvQf882qfOtiXVzbK_DQ8',
    appId: '1:503549612121:ios:06e7c6808658a70db8e148',
    messagingSenderId: '503549612121',
    projectId: 'chat-app-a4cde',
    storageBucket: 'chat-app-a4cde.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-rvbGgMZLIHEvQf882qfOtiXVzbK_DQ8',
    appId: '1:503549612121:ios:06e7c6808658a70db8e148',
    messagingSenderId: '503549612121',
    projectId: 'chat-app-a4cde',
    storageBucket: 'chat-app-a4cde.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtDQ4e7XVhtZGjyp4ZVUo8R8rJtlagiz4',
    appId: '1:503549612121:web:91fef3ac7c06ce93b8e148',
    messagingSenderId: '503549612121',
    projectId: 'chat-app-a4cde',
    authDomain: 'chat-app-a4cde.firebaseapp.com',
    storageBucket: 'chat-app-a4cde.firebasestorage.app',
    measurementId: 'G-C63GEWKNXC',
  );
}
